#!/usr/bin/env bash
# Install VSCode extensions
#
# A list of installed extensions can be obtained with:
# code --list-extensions

if ! type code >/dev/null 2>&1;
then
    echo "VSCode not found, skipping VSCode extensions installation."
    exit 0
fi

code --install-extension asvetliakov.vscode-neovim
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension laravel.vscode-laravel
code --install-extension ms-vscode-remote.remote-containers
code --install-extension sirmspencer.vscode-autohide
code --install-extension vue.volar
