#!/usr/bin/env bash
#
# Install essential programs.

echo "=== $CHEZMOI_SOURCE_FILE ==="

cat <<BREWFILE | brew bundle --no-upgrade --jobs=auto --file=-
brew "bash-language-server"
brew "bat"
brew "composer"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git-delta"
brew "httpie"
brew "mailpit"
brew "neovim", args: ["--HEAD"]
brew "node"
brew "ripgrep"
brew "shellcheck"
brew "tldr"
brew "tree"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "uv"
brew "vivid"
brew "yt-dlp"
cask "balance-lock"
cask "fork"
cask "ghostty"
cask "hammerspoon"
cask "herd"
cask "iina"
cask "keyboardcleantool"
cask "maccy"
cask "markedit"
cask "monitorcontrol"
cask "qlstephen"
cask "windowkeys"
BREWFILE
