#!/usr/bin/env bash
# vim:foldmethod=marker

# System {{{1

# Alert volume to 75% (i.e. don't ruin my music with your loud beeps 😾)
defaults write -g com.apple.sound.beep.volume -float 0.7788008

# Shift-Command-Comma to open System Preferences
defaults write -g NSUserKeyEquivalents -dict-add \
    'System Settings...' '@$,' \
    'Systeemvoorkeuren...' '@$,'

# ColorSlurp {{{1

defaults write com.IdeaPunch.ColorSlurp copyToLastCopyedColorGlobleShortcutKey -dict \
    keycode -int 0 \
    modifiers -int 0
defaults write com.IdeaPunch.ColorSlurp showPickerGlobleShortcutKey -dict \
    keycode -int 0 \
    modifiers -int 0

# Maccy {{{1

# Control-Command-V to show popup
defaults write org.p0deje.Maccy KeyboardShortcuts_popup -string '{"carbonModifiers":4352,"carbonKeyCode":9}'

defaults write org.p0deje.Maccy maxMenuItems -int 12
defaults write org.p0deje.Maccy pasteByDefault -bool true
defaults write org.p0deje.Maccy pinTo -string bottom

# Music {{{1

# Add keyboard shortcuts for repeat and shuffle
defaults write com.apple.Music NSUserKeyEquivalents -dict-add \
    '\033Controls\033Repeat\033All' '@r' \
    '\033Controls\033Repeat\033Off' '@$r' \
    '\033Controls\033Repeat\033One' '@~r' \
    '\033Controls\033Shuffle\033Off' '@$s' \
    '\033Controls\033Shuffle\033On' '@s'

# Safari {{{1

defaults write com.apple.Safari AutoFillPasswords -bool false
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

# Override Command-I in Safari to something less annoying
defaults write com.apple.Safari NSUserKeyEquivalents -dict-add \
    'Share...' '@i' \
    'Deel...' '@i'

# Toggle the sidebar with Control-Command-S, matching other apps
defaults write com.apple.Safari NSUserKeyEquivalents -dict-add \
    'Show Sidebar' '^@s' \
    'Hide Sidebar' '^@s' \
    'Toon navigatiekolom' '^@s' \
    'Verberg navigatiekolom' '^@s'
