#!/usr/bin/env bash
#
# Install essential programs.

cat <<BREWFILE | brew bundle --no-upgrade --file=-
brew "composer"
brew "fish"
brew "fzf"
brew "gh"
brew "git-delta"
brew "httpie"
brew "jq"
brew "mailpit"
brew "neovim"
brew "node"
brew "php"
brew "ripgrep"
brew "tldr"
brew "tree"
brew "yt-dlp"
cask "fork"
cask "hammerspoon"
cask "iterm2@beta"
cask "keyboardcleantool"
cask "maccy"
cask "monitorcontrol"
cask "qlstephen"
cask "rectangle"
cask "sbarex-qlmarkdown"
BREWFILE
